// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Vorion LLC
//
// BASIS Gate v1 — TypeScript type definitions.
//
// This module exports the types that a conformant layer, profile, or runtime
// implementation imports against. The types are derived directly from SPEC.md
// and MUST remain in sync with it. Changes to types that affect semantics
// require a spec revision.

// ---------------------------------------------------------------------------
// Risk levels (referenced from BASIS canonical trust specification)
// ---------------------------------------------------------------------------

/**
 * Risk level identifiers as defined in the BASIS canonical trust specification
 * (`@vorionsys/basis`). Their numeric multipliers, cooldowns, and penalty
 * relationships are fixed canonically; this specification does not redefine
 * them.
 */
export type RiskLevel =
  | "READ"
  | "LOW"
  | "MEDIUM"
  | "HIGH"
  | "CRITICAL"
  | "LIFE_CRITICAL";

/**
 * Trust tier identifiers as defined in the BASIS canonical trust specification.
 * Numeric observation ceilings and promotion delays are fixed canonically.
 */
export type TrustTier = "T0" | "T1" | "T2" | "T3" | "T4" | "T5" | "T6" | "T7";

// ---------------------------------------------------------------------------
// Execution model
// ---------------------------------------------------------------------------

/**
 * How a layer executes relative to action dispatch.
 *
 * - `block`: pipeline pauses; action does not dispatch until the layer returns.
 * - `inline`: layer runs in parallel with dispatch; evidence attaches before
 *   the response is returned to the caller.
 * - `deferred`: layer runs after dispatch; evidence is anchored to the tip and
 *   appended to the proof chain when the layer completes.
 */
export type ExecutionMode = "block" | "inline" | "deferred";

/**
 * Behavioral mode of a layer.
 *
 * - `enforce`: layer verdicts count. A `deny` at `block` prevents dispatch.
 * - `observe`: layer runs and records evidence but its verdict is advisory.
 *   Used for rollout, shadow comparison, and threshold calibration.
 * - `shadow`: layer runs in parallel against a production pipeline to compare
 *   verdicts without influencing the production decision.
 */
export type LayerMode = "enforce" | "observe" | "shadow";

/**
 * Functional band a layer belongs to. Advisory, not enforced by ordering.
 */
export type Band = 1 | 2 | 3 | 4 | 5;

// ---------------------------------------------------------------------------
// Agent action and context
// ---------------------------------------------------------------------------

/**
 * An action an agent is attempting to take. Runtimes extend this type with
 * additional fields; the fields below are the interoperable minimum.
 */
export interface AgentAction {
  /** Globally unique action identifier, generated by the runtime. */
  actionId: string;
  /** Identifier of the agent taking the action. */
  agentId: string;
  /** Risk level of the action, per the canonical risk levels. */
  risk: RiskLevel;
  /** Action class used for deferred-incompatibility checks. */
  classes: ActionClass[];
  /** Opaque payload. Content is layer-specific. */
  payload: unknown;
  /** ISO-8601 timestamp at which the runtime received the action. */
  receivedAt: string;
}

export type ActionClass =
  | "read-only"
  | "internal-effect"
  | "external-recipient"
  | "irreversible-real-world"
  | "multi-hop-chain";

/**
 * Context passed to each layer's `run` function.
 */
export interface GateContext {
  /** The action under evaluation. */
  action: AgentAction;
  /** The evaluating agent's current tier, per the canonical trust specification. */
  agentTier: TrustTier;
  /** The proof-chain tip hash observed when this pipeline began. */
  priorChainTip: string;
  /** Posture identifier in effect for this pipeline. */
  postureId: string;
  /**
   * Evidence accumulated by layers that have already run in this pipeline.
   * Layers with `requires` use this to read prior decisions.
   */
  accumulatedEvidence: ReadonlyArray<LayerEvidenceEnvelope>;
}

// ---------------------------------------------------------------------------
// Evidence
// ---------------------------------------------------------------------------

/**
 * Every decision produces a signed evidence envelope. Layer-specific fields
 * live in `payload`.
 */
export interface LayerEvidenceEnvelope {
  /** Layer identifier that produced this evidence. */
  layerId: string;
  /** Layer version. */
  layerVersion: string;
  /** ISO-8601 timestamp when the layer ran. */
  timestamp: string;
  /** Duration of the layer run in milliseconds. */
  durationMs: number;
  /** Execution mode under which the layer ran. */
  executionMode: ExecutionMode;
  /** Behavioral mode under which the layer ran. */
  layerMode: LayerMode;
  /** Layer-specific structured evidence. MUST be canonical-JSON serializable. */
  payload: Record<string, unknown>;
}

/**
 * A layer's verdict. Exactly one of `allow`, `deny`, or `escalate`.
 */
export type LayerDecision =
  | { verdict: "allow"; evidence: LayerEvidenceEnvelope }
  | { verdict: "deny"; reason: string; evidence: LayerEvidenceEnvelope }
  | {
      verdict: "escalate";
      to: "human" | "higher-tier";
      reason: string;
      evidence: LayerEvidenceEnvelope;
    };

// ---------------------------------------------------------------------------
// The layer interface
// ---------------------------------------------------------------------------

/**
 * A governance layer. Every pluggable check in a BASIS Gate pipeline
 * implements this interface.
 */
export interface GateLayer {
  /** Globally unique layer identifier (e.g. `@basis/identity`, `@acme/finra`). */
  readonly id: string;

  /** Semver version of this layer. */
  readonly version: string;

  /** Functional band. Advisory; see SPEC § 3.4. */
  readonly band: Band;

  /** Preferred execution mode in the absence of overrides. */
  readonly defaultExecution: ExecutionMode;

  /** Layer identifiers that MUST run before this one. */
  readonly requires?: readonly string[];

  /**
   * Risk levels for which this layer MUST be `block` regardless of operator
   * configuration. A conformant runtime MUST enforce this.
   */
  readonly syncRequiredFor?: readonly RiskLevel[];

  /**
   * Industry profile identifiers for which this layer MUST be `block`.
   * A conformant runtime MUST enforce this when the named profile is active.
   */
  readonly blockingIndustries?: readonly string[];

  /**
   * Self-declared latency budget in milliseconds. Runtimes MAY enforce.
   */
  readonly maxDurationMs?: number;

  /**
   * Evaluate the action and return a decision. The runtime signs the evidence
   * envelope and appends it to the proof chain per SPEC § 7.
   */
  run(ctx: GateContext, action: AgentAction): Promise<LayerDecision>;
}

// ---------------------------------------------------------------------------
// Preset and posture configuration
// ---------------------------------------------------------------------------

export type Preset = "lite" | "standard" | "strict" | "full" | "custom";

export interface LayerEntry {
  id: string;
  execution?: ExecutionMode;
  execution_by_risk?: Partial<Record<RiskLevel, ExecutionMode>>;
  mode?: LayerMode;
  config?: Record<string, unknown>;
}

export interface LayerOverride {
  execution?: ExecutionMode;
  execution_by_risk?: Partial<Record<RiskLevel, ExecutionMode>>;
  mode?: LayerMode;
  config?: Record<string, unknown>;
}

/**
 * The document an operator submits to configure a runtime's posture.
 * Serializable to both YAML and canonical JSON without loss.
 */
export interface Posture {
  preset: Preset;
  industry?: string;
  layers?: {
    add?: LayerEntry[];
    remove?: string[];
    override?: Record<string, LayerOverride>;
  };
}

// ---------------------------------------------------------------------------
// Industry profile document
// ---------------------------------------------------------------------------

export interface IndustryProfileReference {
  /** Short citation (regulation name, section, or URL). */
  cite: string;
  /** Human-readable explanation of what the reference mandates. */
  note: string;
}

export interface IndustryProfile {
  id: string;
  version: string;
  description: string;
  jurisdiction: string[];
  minimum_preset: Exclude<Preset, "custom">;
  /** Layer identifiers that MUST be present in the pipeline. */
  required_layers: string[];
  /** Layer id → risk level at which the layer MUST be `block`. */
  required_blocking: Partial<Record<string, RiskLevel>>;
  /** Layer identifiers that MUST NOT run as `deferred`. */
  prohibited_deferred: string[];
  /** Constraints by action class. */
  action_class_rules?: Partial<
    Record<
      ActionClass,
      {
        min_execution_mode?: ExecutionMode;
        required_layers?: string[];
      }
    >
  >;
  /** Citations to the regulatory basis for each constraint. */
  references: IndustryProfileReference[];
}

// ---------------------------------------------------------------------------
// Proof-chain event types (SPEC § 7)
// ---------------------------------------------------------------------------

/**
 * Tip commit event — produced synchronously when `block` and `inline` layers
 * have completed and the action is ready to dispatch.
 */
export interface TipCommitEvent {
  kind: "tip-commit";
  actionId: string;
  priorChainTip: string;
  tipHash: string;
  syncEvidence: LayerEvidenceEnvelope[];
  tipSignature: string;
  signedBy: string;
  createdAt: string;
}

/**
 * Chain extension event — produced when a deferred layer completes. Each
 * event anchors to the tip hash captured at synchronous commit time.
 */
export interface ChainExtensionEvent {
  kind: "chain-extension";
  actionId: string;
  anchorTip: string;
  layerId: string;
  layerVersion: string;
  evidence: LayerEvidenceEnvelope;
  layerSignature: string;
  runtimeAttestation: string;
  createdAt: string;
}

/**
 * Deferred timeout event — produced when a deferred layer does not complete
 * within its deferral window.
 */
export interface DeferredTimeoutEvent {
  kind: "deferred-timeout";
  actionId: string;
  anchorTip: string;
  layerId: string;
  declaredDeadline: string;
  signedBy: string;
  createdAt: string;
}

/**
 * Posture load event — produced when a runtime loads or reloads its posture.
 */
export interface PostureLoadEvent {
  kind: "posture-load";
  postureId: string;
  posture: Posture;
  resolvedPipeline: string[];
  postureSignature: string;
  signedBy: string;
  createdAt: string;
}

export type ProofChainEvent =
  | TipCommitEvent
  | ChainExtensionEvent
  | DeferredTimeoutEvent
  | PostureLoadEvent;

// ---------------------------------------------------------------------------
// Specification metadata
// ---------------------------------------------------------------------------

export const SPEC_VERSION = "1.0-draft";
export const SPEC_NAME = "BASIS Gate v1";

/**
 * Canonical-JSON serializer contract. Implementations MUST produce
 * key-sorted, whitespace-free JSON. The reference implementation is
 * defined in the runtime package, not here.
 */
export interface CanonicalJsonSerializer {
  serialize(value: unknown): string;
}
